In [37]:
# 1. Load data from the file 'jester-data-1.csv'
# Note: 99 denotes that the user hasn't been labelled it. Therefore don't
# use then in training.

import pandas as pd
df = pd.read_csv("jester-data-1.csv", header=None)
df.head(5)

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,74,-7.82,8.79,-9.66,-8.16,-7.52,-8.50,-9.85,4.17,-8.98,...,2.82,99.00,99.00,99.00,99.00,99.00,-5.63,99.00,99.00,99.00
1,100,4.08,-0.29,6.36,4.37,-2.38,-9.66,-0.73,-5.34,8.88,...,2.82,-4.95,-0.29,7.86,-0.19,-2.14,3.06,0.34,-4.32,1.07
2,49,99.00,99.00,99.00,99.00,9.03,9.27,9.03,9.27,99.00,...,99.00,99.00,99.00,9.08,99.00,99.00,99.00,99.00,99.00,99.00
3,48,99.00,8.35,99.00,99.00,1.80,8.16,-2.82,6.21,99.00,...,99.00,99.00,99.00,0.53,99.00,99.00,99.00,99.00,99.00,99.00
4,91,8.50,4.61,-4.17,-5.39,1.36,1.60,7.04,4.61,-0.44,...,5.19,5.58,4.27,5.19,5.73,1.55,3.11,6.55,1.80,1.60

In [38]:
# 2. Label 10% of the dataset cells as 99, to denote they are part of the
# validation set.

# Make a copy of the data frame.
df_validation = df.copy()
df_validation.head(5)

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,74,-7.82,8.79,-9.66,-8.16,-7.52,-8.50,-9.85,4.17,-8.98,...,2.82,99.00,99.00,99.00,99.00,99.00,-5.63,99.00,99.00,99.00
1,100,4.08,-0.29,6.36,4.37,-2.38,-9.66,-0.73,-5.34,8.88,...,2.82,-4.95,-0.29,7.86,-0.19,-2.14,3.06,0.34,-4.32,1.07
2,49,99.00,99.00,99.00,99.00,9.03,9.27,9.03,9.27,99.00,...,99.00,99.00,99.00,9.08,99.00,99.00,99.00,99.00,99.00,99.00
3,48,99.00,8.35,99.00,99.00,1.80,8.16,-2.82,6.21,99.00,...,99.00,99.00,99.00,0.53,99.00,99.00,99.00,99.00,99.00,99.00
4,91,8.50,4.61,-4.17,-5.39,1.36,1.60,7.04,4.61,-0.44,...,5.19,5.58,4.27,5.19,5.73,1.55,3.11,6.55,1.80,1.60

In [39]:
# Calculate the number of rows, columns and cells in the data set.
users = df_validation.shape[0]
jokes = df_validation.shape[1]
cells = users * jokes

print('Users:\t' + str(users))
print('Jokes:\t' + str(jokes))
print('Cells:\t' + str(cells))

Users:	24983
Jokes:	101
Cells:	2523283

In [40]:
# Get number cells that require changing.

# iloc: 'Purely integer-location based indexing for selection by position'.
# iloc: http://pandas.pydata.org/pandas-docs/version/0.17.0/generated/pandas.DataFrame.iloc.html

cells_not_specified = (df_validation.iloc[:,:] == 99).sum().sum()
cells_not_specified_percent = (cells_not_specified / cells) * 100

print('Not specified count:\t' + str(cells_not_specified))
print('Not specified percent:\t' + str(cells_not_specified_percent))

cells_specified = cells - cells_not_specified
cells_to_change = round(cells_specified * 0.1).astype(int)

print('Cells specified:\t' + str(cells_specified))
print('Cells to change\t:\t' + str(cells_to_change))

Not specified count:	687926
Not specified percent:	27.26313298983903
Cells specified:	1835357
Cells to change	:	183536

In [41]:
# Change 10% of cells to '99'.
import random as rand

row = 0
col = 0
for x in range(0, cells_to_change):  
    while (df_validation.iloc[row, col]) == 99:
        row = rand.randint(0, users - 1)
        col = rand.randint(0, jokes - 1)
    df_validation.at[row, col] = 99    
    
print('Not specified count after: ' + str((df_validation.iloc[:,:] == 99).sum().sum()))

df_validation.head()

Not specified count after: 871462

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,99,-7.82,8.79,99.00,-8.16,-7.52,99.00,-9.85,4.17,-8.98,...,2.82,99.00,99.00,99.00,99.00,99.00,-5.63,99.00,99.00,99.00
1,100,99.00,-0.29,6.36,4.37,-2.38,-9.66,-0.73,-5.34,8.88,...,99.00,-4.95,-0.29,7.86,-0.19,-2.14,3.06,0.34,-4.32,1.07
2,49,99.00,99.00,99.00,99.00,9.03,9.27,9.03,9.27,99.00,...,99.00,99.00,99.00,9.08,99.00,99.00,99.00,99.00,99.00,99.00
3,48,99.00,8.35,99.00,99.00,1.80,8.16,-2.82,6.21,99.00,...,99.00,99.00,99.00,0.53,99.00,99.00,99.00,99.00,99.00,99.00
4,91,8.50,4.61,-4.17,-5.39,1.36,1.60,7.04,4.61,-0.44,...,99.00,5.58,4.27,5.19,5.73,1.55,3.11,99.00,1.80,1.60

In [42]:
# 3. Use latent factor modeling to infer the hidden ratings of the users.
# Generate initial random data.
import numpy as np

factors = 3

latent_item_features = np.random.random((jokes, factors))
latent_user_preferences = np.random.random((users, factors))

print('Latent item features = ' + repr(latent_item_features))
print('Latent user preferences = ' + repr(latent_user_preferences))

Latent item features = array([[0.31553218, 0.35375843, 0.42128843],
       [0.83733677, 0.63102883, 0.4861513 ],
       [0.41308771, 0.63552616, 0.02460905],
       [0.56726126, 0.1933566 , 0.77156232],
       [0.97379705, 0.7133205 , 0.03880881],
       [0.05399391, 0.11352083, 0.95802275],
       [0.24578754, 0.31499537, 0.52186427],
       [0.33398775, 0.44690347, 0.98898567],
       [0.00136793, 0.23378431, 0.43043728],
       [0.00446899, 0.40568992, 0.42717097],
       [0.97985558, 0.49165449, 0.21749641],
       [0.14609495, 0.43437843, 0.9722517 ],
       [0.70326123, 0.14522801, 0.15986105],
       [0.27442175, 0.27011004, 0.80743314],
       [0.00183   , 0.86266868, 0.86927456],
       [0.20648025, 0.10005742, 0.90066547],
       [0.67983417, 0.9100762 , 0.86038761],
       [0.5955261 , 0.65983189, 0.44209573],
       [0.89968553, 0.29560511, 0.4100669 ],
       [0.39845782, 0.44568366, 0.78919017],
       [0.03554156, 0.74181618, 0.49765141],
       [0.69455884, 0.68587731, 0.26136882],
       [0.45626993, 0.74961121, 0.33170959],
       [0.4800134 , 0.43947559, 0.12296607],
       [0.29521337, 0.50956864, 0.67423305],
       [0.3927618 , 0.7204693 , 0.9617218 ],
       [0.14356094, 0.09510421, 0.40700495],
       [0.90088473, 0.6028072 , 0.89185604],
       [0.73152858, 0.5215155 , 0.25968908],
       [0.79002096, 0.82871687, 0.03497972],
       [0.72521167, 0.91668221, 0.84030385],
       [0.18956714, 0.69233738, 0.57922744],
       [0.04346604, 0.09691264, 0.94677596],
       [0.71723515, 0.12780705, 0.28629579],
       [0.73491365, 0.11748588, 0.14319833],
       [0.83898901, 0.33066699, 0.29259432],
       [0.97488106, 0.73697571, 0.54505945],
       [0.63980055, 0.87219823, 0.56231757],
       [0.64179113, 0.32454815, 0.48003644],
       [0.13801319, 0.59631915, 0.00738846],
       [0.97421547, 0.54559482, 0.19103634],
       [0.04376875, 0.89150597, 0.84861569],
       [0.59990837, 0.90459043, 0.04982592],
       [0.72434747, 0.78968694, 0.42893286],
       [0.07479738, 0.66089974, 0.82516817],
       [0.17970919, 0.97647844, 0.91366429],
       [0.02056912, 0.04912828, 0.26611401],
       [0.8352944 , 0.95120887, 0.95803987],
       [0.11399591, 0.68109485, 0.14907637],
       [0.98178064, 0.65483962, 0.25813532],
       [0.93028324, 0.9351535 , 0.47970416],
       [0.31047459, 0.0111345 , 0.613885  ],
       [0.98273488, 0.15659859, 0.40492352],
       [0.77582803, 0.40195422, 0.99749875],
       [0.67249413, 0.69600247, 0.85757149],
       [0.46419898, 0.69108326, 0.11149939],
       [0.84298885, 0.25790107, 0.63166411],
       [0.39687524, 0.15565222, 0.57606508],
       [0.16042987, 0.09005333, 0.27362278],
       [0.53112818, 0.6530483 , 0.49803604],
       [0.34875803, 0.93503811, 0.82185888],
       [0.35394441, 0.7303937 , 0.09926645],
       [0.8964375 , 0.93192872, 0.23481193],
       [0.3349139 , 0.77579487, 0.93398916],
       [0.65803499, 0.26592458, 0.77462926],
       [0.9718125 , 0.47447298, 0.43945181],
       [0.7811515 , 0.73897606, 0.76028935],
       [0.80311414, 0.7947117 , 0.55797609],
       [0.23146069, 0.63024123, 0.43352661],
       [0.26770274, 0.5670475 , 0.14600788],
       [0.58394408, 0.40591274, 0.80423358],
       [0.09374061, 0.21422818, 0.13389545],
       [0.3494449 , 0.47283663, 0.43321858],
       [0.60860812, 0.67778804, 0.88170347],
       [0.16800189, 0.59092416, 0.01923877],
       [0.40655367, 0.25757609, 0.63690887],
       [0.49892842, 0.38953289, 0.81544156],
       [0.46272181, 0.97298909, 0.22217463],
       [0.29268089, 0.90655866, 0.50756815],
       [0.36158489, 0.65871652, 0.2805186 ],
       [0.79159653, 0.49745656, 0.05785008],
       [0.54312416, 0.68723648, 0.8500843 ],
       [0.83472478, 0.64859468, 0.09521386],
       [0.61036857, 0.70068124, 0.66728609],
       [0.49450039, 0.19197984, 0.69756528],
       [0.09337011, 0.73693923, 0.14482129],
       [0.88224286, 0.07942859, 0.87532876],
       [0.80696225, 0.41428112, 0.96269499],
       [0.13676674, 0.63019346, 0.75869563],
       [0.64054025, 0.07827969, 0.6231151 ],
       [0.01620826, 0.05640838, 0.67959714],
       [0.42473267, 0.2711352 , 0.46422096],
       [0.99571593, 0.06679538, 0.47001787],
       [0.04968935, 0.36536562, 0.96692998],
       [0.61775435, 0.17443256, 0.53925465],
       [0.87394502, 0.06631009, 0.27184979],
       [0.598123  , 0.08774958, 0.93851718],
       [0.23813661, 0.62212441, 0.32772285],
       [0.5092945 , 0.10562777, 0.02552354],
       [0.84596154, 0.78157855, 0.12356414],
       [0.04496188, 0.79745209, 0.44082311]])
Latent user preferences = array([[0.04467441, 0.5246458 , 0.35243874],
       [0.88050013, 0.10435986, 0.07523129],
       [0.85258946, 0.39652766, 0.51234777],
       ...,
       [0.59053733, 0.76728571, 0.00311884],
       [0.94497803, 0.63836815, 0.47279615],
       [0.24127202, 0.12619044, 0.92900842]])

In [43]:
# Predict ratings function.
def predict_rating(user_row, item_row):
    """ Predict a rating given a user_row and an item_row. """
    
    user_values = latent_user_preferences[user_row]
    item_values = latent_item_features[item_row]
    return user_values.dot(item_values)

In [44]:
# Training function.
def train(user_row, item_row, rating, alpha = 0.0001):
    """ Adapt the values of user_preferences and item_factors to match
    the ones predicted by the users. """
    
    err = alpha * (rating - predict_rating(user_row, item_row))
    latent_user_preferences[user_row] += err * latent_item_features[item_row]
    latent_item_features[item_row] += err * latent_user_preferences[user_row]
    return err

In [ ]:
# Train function. Ignore '99' values which indicates
# Either that the item has not been specified or it is part of the
# validation set.

def sgd_svd(iterations = 100):
    for i in range(0, iterations):
        training_errors = []
        for user_row in range(0, users):
            for joke_col in range(0, jokes):
                rating = df_validation.iloc[user_row][joke_col]
                if (not np.isnan(rating) and not rating == 99):
                    training_errors.append(train(user_row, joke_col, rating))
        if (i % 10 == 0):
            print("Training MSE, " + str(i) + ": " + str((np.array(training_errors) ** 2).mean()))

In [ ]:
# Run the training function and print out updated tables.

sgd_svd()

print('Latent item features = ' + repr(latent_item_features))
print('Latent user preferences = ' + repr(latent_user_preferences))

In [ ]:
# 4. Calculate the performance of the algorithm on the validation dataset.

validation_error = []
for user in range(0, 20):
    for joke in range(0, jokes):
        rating_training_data = df.iloc[user][joke]
        rating_validation_data = df_validation.iloc[user][joke]
        if (not rating_training_data == rating_validation_data):
            prediction = predict_rating(user, joke)
            validation_error.append(rating_training_data - predict_rating(user, joke))
print("Validation MSE: " + str((np.array(validation_error) ** 2).mean()))